name: kusto-color-themes-pr-validation

on:
  pull_request:
    branches:
      - master
    paths:
      - 'kusto-color-themes/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: kusto-color-themes

    steps:
      - uses: actions/checkout@v2

      - name: Ensure all contributed themes exist in repo
        uses: kusto-color-themes/verify@v1
        with:
          working-directory: kusto-color-themes
