name: kusto-extensions-pack-publish

on:
  push:
    branches:
      - master
    paths:
      - 'kusto-extensions-pack/**'
      - '.github/workflows/kusto-extensions-pack-publish.yml'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: kusto-extensions-pack

    steps:
      - uses: actions/checkout@v2

      - name:  'Automated Version Bump'
        uses:  '.github/actions/gh-action-bump-version-master'
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          PACKAGEJSON_DIR:  'kusto-extensions-pack'
        with:
          default: patch
          tag-prefix: kusto-extensions-pack-v
          # Don't push this commit, because we might not have latest master.
          # We'll fetch, merge, and push at the end.
          push: false

      - name: Publish VS Code Extension
        uses: HaaLeo/publish-vscode-extension@v0
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          packagePath: ./kusto-extensions-pack

      - name: Push version bump commit
        run: |
          git status
          git pull --rebase
          git status
          git push
